#! /bin/bash

script_dir=$(dirname $(readlink -e $BASH_SOURCE))

. ${script_dir}/internal/setup-paths > /dev/null 2>&1

${script_dir}/internal/gen-oe-setup.py ${@} --base-path ${REPO_DIR}

test -e .setup_build || exit 1

. .setup_build > /dev/null

mv ${REPO_DIR}/.setup_build ${REPO_DIR}/.setup_run

echo ". ${script_dir}/internal/setup-paths > /dev/null 2>&1" > SOURCE_THIS
echo ${EXEC} >> SOURCE_THIS

bitbake -p || exit 1

${script_dir}/internal/add-layers.py --layers $(printf %s $BBLAYERS)

mv conf/local.conf conf/local.conf.bk

echo "## The following variables have been automatically added from the" > conf/local.conf
echo "## init-new-build script" >> conf/local.conf
echo "" >> conf/local.conf
echo "MACHINE='${MACHINE}'" >> conf/local.conf
echo "DISTRO='${DISTRO}'" >> conf/local.conf
echo "DL_DIR='${DL_DIR}'" >> conf/local.conf
echo "SSTATE_DIR='${SSTATE_DIR}'" >> conf/local.conf
echo "" >> conf/local.conf

cat conf/local.conf.bk >> conf/local.conf
rm conf/local.conf.bk


cat <<EOF

Your build has been setup, please source the file "source_build" to
get started.

. ${BUILDDIR}/SOURCE_THIS

EOF
