#! /bin/sh

THIS_SCRIPT=$BASH_SOURCE

if [ "$0" = "$THIS_SCRIPT" ]; then
   echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'"
   exit 1
fi

# Source the environment script and start the build
. ${BUILD_DIR}/openembedded/oe-core.git/oe-init-build-env \
	${BUILD_DIR}/openembedded/build \
	${BUILD_DIR}/openembedded/bitbake.git
