#! /bin/bash

THIS_SCRIPT=$BASH_SOURCE

if [ "$0" = "$THIS_SCRIPT" ]; then
   echo "Error: This script needs to be sourced. Please run as '. $THIS_SCRIPT'"
   exit 1
fi

cwd=$(pwd)

until [[ $(ls openembedded) && $(ls .repo) ]]; do
	cd ..

	if [[ $(pwd) = "/" ]]
	then
		echo "Failed to find initialised repo directory"
		cd ${cwd}
		exit 1
	fi
done

REPO_DIR=$(pwd)

cd $cwd

PATH=${REPO_DIR}/.repo/manifests/scripts:$PATH

export REPO_DIR
export PATH
